spring:
  main:
    banner-mode: off
  shell:
    noninteractive:
      primary-command: catalog
## disable console logging
logging:
  pattern:
    console:
## log debug from a cli
  file:
    name: shell.log
  level:
    # root: debug
    org:
      jline: debug
      springframework:
        shell: debug
