// Generated by jextract

package org.springframework.shell.treesitter.ts;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TSPoint {
 *     uint32_t row;
 *     uint32_t column;
 * }
 * }
 */
public class TSPoint {

    TSPoint() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TreeSitter.C_INT.withName("row"),
        TreeSitter.C_INT.withName("column")
    ).withName("TSPoint");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt row$LAYOUT = (OfInt)$LAYOUT.select(groupElement("row"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static final OfInt row$layout() {
        return row$LAYOUT;
    }

    private static final long row$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static final long row$offset() {
        return row$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static int row(MemorySegment struct) {
        return struct.get(row$LAYOUT, row$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t row
     * }
     */
    public static void row(MemorySegment struct, int fieldValue) {
        struct.set(row$LAYOUT, row$OFFSET, fieldValue);
    }

    private static final OfInt column$LAYOUT = (OfInt)$LAYOUT.select(groupElement("column"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t column
     * }
     */
    public static final OfInt column$layout() {
        return column$LAYOUT;
    }

    private static final long column$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t column
     * }
     */
    public static final long column$offset() {
        return column$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t column
     * }
     */
    public static int column(MemorySegment struct) {
        return struct.get(column$LAYOUT, column$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t column
     * }
     */
    public static void column(MemorySegment struct, int fieldValue) {
        struct.set(column$LAYOUT, column$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

