// Generated by jextract

package org.springframework.shell.treesitter.ts;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TSQueryMatch {
 *     uint32_t id;
 *     uint16_t pattern_index;
 *     uint16_t capture_count;
 *     const TSQueryCapture *captures;
 * }
 * }
 */
public class TSQueryMatch {

    TSQueryMatch() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TreeSitter.C_INT.withName("id"),
        TreeSitter.C_SHORT.withName("pattern_index"),
        TreeSitter.C_SHORT.withName("capture_count"),
        TreeSitter.C_POINTER.withName("captures")
    ).withName("TSQueryMatch");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t id
     * }
     */
    public static final OfInt id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t id
     * }
     */
    public static int id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t id
     * }
     */
    public static void id(MemorySegment struct, int fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final OfShort pattern_index$LAYOUT = (OfShort)$LAYOUT.select(groupElement("pattern_index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t pattern_index
     * }
     */
    public static final OfShort pattern_index$layout() {
        return pattern_index$LAYOUT;
    }

    private static final long pattern_index$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t pattern_index
     * }
     */
    public static final long pattern_index$offset() {
        return pattern_index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t pattern_index
     * }
     */
    public static short pattern_index(MemorySegment struct) {
        return struct.get(pattern_index$LAYOUT, pattern_index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t pattern_index
     * }
     */
    public static void pattern_index(MemorySegment struct, short fieldValue) {
        struct.set(pattern_index$LAYOUT, pattern_index$OFFSET, fieldValue);
    }

    private static final OfShort capture_count$LAYOUT = (OfShort)$LAYOUT.select(groupElement("capture_count"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t capture_count
     * }
     */
    public static final OfShort capture_count$layout() {
        return capture_count$LAYOUT;
    }

    private static final long capture_count$OFFSET = 6;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t capture_count
     * }
     */
    public static final long capture_count$offset() {
        return capture_count$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t capture_count
     * }
     */
    public static short capture_count(MemorySegment struct) {
        return struct.get(capture_count$LAYOUT, capture_count$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t capture_count
     * }
     */
    public static void capture_count(MemorySegment struct, short fieldValue) {
        struct.set(capture_count$LAYOUT, capture_count$OFFSET, fieldValue);
    }

    private static final AddressLayout captures$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("captures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const TSQueryCapture *captures
     * }
     */
    public static final AddressLayout captures$layout() {
        return captures$LAYOUT;
    }

    private static final long captures$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const TSQueryCapture *captures
     * }
     */
    public static final long captures$offset() {
        return captures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const TSQueryCapture *captures
     * }
     */
    public static MemorySegment captures(MemorySegment struct) {
        return struct.get(captures$LAYOUT, captures$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const TSQueryCapture *captures
     * }
     */
    public static void captures(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(captures$LAYOUT, captures$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

