// Generated by jextract

package org.springframework.shell.treesitter.ts;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TSRange {
 *     TSPoint start_point;
 *     TSPoint end_point;
 *     uint32_t start_byte;
 *     uint32_t end_byte;
 * }
 * }
 */
public class TSRange {

    TSRange() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        TSPoint.layout().withName("start_point"),
        TSPoint.layout().withName("end_point"),
        TreeSitter.C_INT.withName("start_byte"),
        TreeSitter.C_INT.withName("end_byte")
    ).withName("TSRange");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout start_point$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("start_point"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TSPoint start_point
     * }
     */
    public static final GroupLayout start_point$layout() {
        return start_point$LAYOUT;
    }

    private static final long start_point$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TSPoint start_point
     * }
     */
    public static final long start_point$offset() {
        return start_point$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TSPoint start_point
     * }
     */
    public static MemorySegment start_point(MemorySegment struct) {
        return struct.asSlice(start_point$OFFSET, start_point$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TSPoint start_point
     * }
     */
    public static void start_point(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, start_point$OFFSET, start_point$LAYOUT.byteSize());
    }

    private static final GroupLayout end_point$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("end_point"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TSPoint end_point
     * }
     */
    public static final GroupLayout end_point$layout() {
        return end_point$LAYOUT;
    }

    private static final long end_point$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TSPoint end_point
     * }
     */
    public static final long end_point$offset() {
        return end_point$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TSPoint end_point
     * }
     */
    public static MemorySegment end_point(MemorySegment struct) {
        return struct.asSlice(end_point$OFFSET, end_point$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TSPoint end_point
     * }
     */
    public static void end_point(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, end_point$OFFSET, end_point$LAYOUT.byteSize());
    }

    private static final OfInt start_byte$LAYOUT = (OfInt)$LAYOUT.select(groupElement("start_byte"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t start_byte
     * }
     */
    public static final OfInt start_byte$layout() {
        return start_byte$LAYOUT;
    }

    private static final long start_byte$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t start_byte
     * }
     */
    public static final long start_byte$offset() {
        return start_byte$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t start_byte
     * }
     */
    public static int start_byte(MemorySegment struct) {
        return struct.get(start_byte$LAYOUT, start_byte$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t start_byte
     * }
     */
    public static void start_byte(MemorySegment struct, int fieldValue) {
        struct.set(start_byte$LAYOUT, start_byte$OFFSET, fieldValue);
    }

    private static final OfInt end_byte$LAYOUT = (OfInt)$LAYOUT.select(groupElement("end_byte"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t end_byte
     * }
     */
    public static final OfInt end_byte$layout() {
        return end_byte$LAYOUT;
    }

    private static final long end_byte$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t end_byte
     * }
     */
    public static final long end_byte$offset() {
        return end_byte$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t end_byte
     * }
     */
    public static int end_byte(MemorySegment struct) {
        return struct.get(end_byte$LAYOUT, end_byte$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t end_byte
     * }
     */
    public static void end_byte(MemorySegment struct, int fieldValue) {
        struct.set(end_byte$LAYOUT, end_byte$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

