name: Setup Java
description: Installs needed jdk version
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: |
          22
          17
        cache: gradle
