[appendix]
[#appendix-tech-intro-tui]
== Terminal UI
ifndef::snippets[:snippets: ../../test/java/org/springframework/shell/docs]

This is a technical introduction to _UI Framework_.

_UI Framework_ is a toolkit to build rich console apps.

=== Control
_Control_ draws something into a screen with a given bounds.

=== View
_View_ extends _Control_ providing integration into event loop.

=== EventLoop
_EventLoop_ is a central system handling eventing in a framework.

=== Screen
_Screen_ is an abstraction providing higher level concept to draw something
into a terminal.

=== Key Handling
Handles incoming key events.

=== Mouse Handling
Handles incoming mouse events.

[#appendix-tech-intro-tui-catalogapp]
=== Catalog App
Catalog application is showing various ways how Terminal UI Framework can be used.
In this section we discuss how this application works. It can be considered to be
a reference application as its using most of the features available and tries
to follow best practices.

==== Create Scenario
Every `Scenario` essentially is a sample code of a `View` as that's what catalog
app demonstrates.
