name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: linux jdk17
            java: 17
            disable-samples: true
    name: CI Build ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build
        env:
          DISABLE_SAMPLES: ${{ matrix.disable-samples }}
        run: ./mvnw -B package
  publish:
    if: github.repository_owner == 'spring-projects'
    needs: [build]
    name: Call Publish Snapshot
    uses: spring-projects/spring-shell/.github/workflows/ci-publish.yml@main
    secrets:
      jfArtifactorySpring: ${{ secrets.JF_ARTIFACTORY_SPRING }}
