name: e2e

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: win
            os: windows-2019
            graal: 22.0.0.2
          - nickname: macos
            os: macos-latest
            graal: 22.0.0.2
          - nickname: linux
            os: ubuntu-latest
            graal: 22.0.0.2
    name: E2E ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 11
          components: native-image
          set-java-home: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          ./mvnw clean package -Pnative
      - uses: actions/upload-artifact@v2
        with:
          name: spring-shell-samples-${{ matrix.nickname }}
          retention-days: 1
          path: |
            spring-shell-samples/target/*.jar
            spring-shell-samples/target/spring-shell-samples
            spring-shell-samples/target/spring-shell-samples.exe
      - name: compile e2e module
        working-directory: e2e/spring-shell-e2e
        run: |
          npm install
          npm run build
      - name: run e2e tests
        working-directory: e2e/spring-shell-e2e-tests
        run: |
          npm install
          npm test
