name: e2e

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: win
            os: windows-latest
            graal: 22.2.0
    name: E2E ${{ matrix.nickname }}
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graal }}
          java-version: 17
          components: native-image
          set-java-home: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          ./mvnw clean package -Pnativex
      - uses: actions/upload-artifact@v2
        with:
          name: spring-shell-samples-${{ matrix.nickname }}
          retention-days: 1
          path: |
            spring-shell-samples/target/*.jar
            spring-shell-samples/target/spring-shell-samples
            spring-shell-samples/target/spring-shell-samples.exe
      - name: compile e2e module
        working-directory: e2e/spring-shell-e2e
        run: |
          npm install
          npm run build
      - name: run e2e tests
        working-directory: e2e/spring-shell-e2e-tests
        run: |
          npm install
          npm test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: e2e/spring-shell-e2e-tests/junit.xml
